### ISSUE TITLE
[Feature]: Support VSS version 4.0

### ISSUE THREAD

**Issue by BjoernAtBosch** [eclipse-velocitas/vehicle-model-generator#41]
### Description

Extend model generator to support current VSS version(s)

**Comment by BjoernAtBosch** [comment]
This was reported in https://github.com/eclipse-velocitas/vehicle-app-python-template/issues/188
Split this into separate issue for better traceability

**Comment by eriksven** [comment]
As an update, there is the ongoing PR #51 by @lukasmittag

**Comment by dennismeister93** [comment]
Implemented with #51 :)
